# ===================================================================
# Spring Boot configuration for the "gae" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  port: ${PORT}
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 'jdbc:mysql://google/pizza_store?cloudSqlInstance=ody-offer-letter:us-east4:offer-letter-sql&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false'
    username: 'pizzaAdmin'
    password: '1234qwer!@#$QWER'
    hikari:
      maximumPoolSize: 8
