apiVersion: v1
kind: Service
metadata:
  name: pizzastore
  namespace: pizza-store
  labels:
    app: pizzastore
spec:
  selector:
    app: pizzastore
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
