apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzastore
  namespace: pizza-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzastore
      version: 'v1'
  template:
    metadata:
      labels:
        app: pizzastore
        version: 'v1'
    spec:
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              while true
              do
                rt=$(nc -z -w 1 35.199.39.96 3306)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB 35.199.39.96 is not yet reachable; sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: pizzastore-app
          image: gcr.io/ody-offer-letter/pizzastore
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://35.199.39.96:3306/pizzastore?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
              # value: jdbc:mysql://pizzastore-mysql.pizza-store.svc.cluster.local:3306/pizzastore?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
            - name: SPRING_DATA_JEST_URI
              value: http://pizzastore-elasticsearch.pizza-store.svc.cluster.local:9200
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: http://pizzastore-elasticsearch.pizza-store.svc.cluster.local:9200
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '2Gi'
              cpu: '2'
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/info
              port: http
            initialDelaySeconds: 120
